"""update bookmarks

Revision ID: 644f43782cd5
Revises: 52bb6cb8f8d9
Create Date: 2024-08-19 11:54:34.782500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644f43782cd5'
down_revision = '52bb6cb8f8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('bookmark',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('bookmark',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###
